#!/bin/bash

set_aliases() {
	alias ll='ls -l'
	alias lla='ls -la'
}

set_prompt() {
	# if inetractive shell change prompt
	if [ "$PS1" ]; then
		local GREEN_VLAN=10
		local RED_VLAN=20
		local YELLOW_VLAN=66

		local DEFAULT='\[\e[00m\]'

		local REDB='\[\e[1;31m\]'
		local GREENB='\[\e[1;32m\]'
		local YELLOWB='\[\e[1;33m\]'

		# magenta
		local USER_COLOR='\[\e[0;35m\]'

		# blue bold
		local DIR_COLOR='\[\e[1;34m\]'
		
		local COLOR=$DEFAULT
		local VLAN=$(ip route get 192.168.1.1 | awk '{print $7; exit}' | awk -F. '{print $3; exit}')
		case "$VLAN" in
			"$GREEN_VLAN") COLOR=$GREENB ;;
			"$RED_VLAN") COLOR=$REDB ;;
			"$YELLOW_VLAN") COLOR=$YELLOWB ;;
		esac

		if [ "$COLOR" ]; then
			PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}${USER_COLOR}\u${COLOR}@${COLOR}\h${DEFAULT}:${DIR_COLOR}\w${DEFAULT}\$ "
		fi
	fi
}

set_aliases
set_prompt
