#!/bin/bash

set_aliases() {
	alias ll='ls -l'
	alias lla='ls -la'
	alias dpn='sudo docker ps --format "{{.Names}}"'
}

set_prompt() {
	# if inetractive shell change prompt
	if [ "$PS1" ]; then
		local GREEN_VLAN=10
		local RED_VLAN=20
		local YELLOW_VLAN=66

		local DEFAULT='\[\e[00m\]'

		local RED='\[\e[0;31m\]'
		local GREEN='\[\e[0;32m\]'
		local YELLOW='\[\e[0;33m\]'
		local BLUE='\[\e[0;36m\]'

		# magenta
		local USER_COLOR='\[\e[0;35m\]'

		# blue bold
		local DIR_COLOR='\[\e[1;34m\]'
		
		local COLOR=$DEFAULT
		local ON_LOCAL_NET=false

		if [ $(ip route get 192.168.1.1 | awk '{print $7; exit}' | awk -F. '{print $1$2; exit}') == "192168" ]; then
			ON_LOCAL_NET=true
		fi

		if [ "$ON_LOCAL_NET" == true ]; then
			local VLAN=$(ip route get 192.168.1.1 | awk '{print $7; exit}' | awk -F. '{print $3; exit}')
			case "$VLAN" in
				"$GREEN_VLAN") COLOR=$GREEN ;;
				"$RED_VLAN") COLOR=$RED ;;
				"$YELLOW_VLAN") COLOR=$YELLOW ;;
			esac
		else
			COLOR=$BLUE
		fi

		if [ "$COLOR" ]; then
			PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}${USER_COLOR}\u${COLOR}@${COLOR}\h${DEFAULT}:${DIR_COLOR}\w${DEFAULT}\$ "
		fi
	fi
}

set_aliases
set_prompt
