---
- name: Provision bashrc
  hosts: "{{ target_host }}"
  vars_files:
    - ../vars/globals.yaml  
    - ../vars/bashrc.yaml
  tasks:
    - name: Create remote bashrc directory
      ansible.builtin.file:
        path: '{{ bashrc_remote_dir }}'
        state: directory

    - name: Copy global bashrc
      ansible.builtin.copy:
        src: '{{ bashrc_global_path }}'
        dest: '{{ bashrc_remote_dir }}'
        backup: true
      when: bashrc_global_path is exists

    - name: Copy local bashrc
      ansible.builtin.copy:
        src: '{{ bashrc_local_path }}'
        dest: '{{ bashrc_remote_dir }}'
        backup: true
      when: bashrc_local_path is exists

    - name: Source global bashrc
      ansible.builtin.lineinfile:
        path: '{{ bashrc_remote_path }}'
        line: '. {{ bashrc_remote_dir }}/{{ bashrc_global_file }}'
        state: present
        create: true
      when: bashrc_global_path is exists

    - name: Source local bashrc
      ansible.builtin.lineinfile:
        path: '{{ bashrc_remote_path }}'
        line: '. {{ bashrc_remote_dir }}/{{ bashrc_local_file }}'
        state: present
        create: true
      when: bashrc_local_path is exists

    - name: Source bashrc in main bashrc
      ansible.builtin.lineinfile:
        path: '~/.bashrc'
        line: '. {{ bashrc_remote_path }}'
        state: present
      when: bashrc_remote_path is exists
