---
- name: Provision bashrc
  hosts: "{{ target_host }}"
  vars_files:
    - ../vars/globals.yaml  
    - ../vars/bashrc.yaml
  tasks:
    - name: Create remote bashrc directory
      ansible.builtin.file:
        path: '{{ bashrc_remote_dir }}'
        state: directory

    - name: Copy global bashrc
      ansible.builtin.copy:
        src: '{{ bashrc_global_path }}'
        dest: '{{ bashrc_remote_dir }}'
        backup: true
      register: bashrc_global_copy

    - name: Copy local bashrc
      ansible.builtin.copy:
        src: '{{ bashrc_local_path }}'
        dest: '{{ bashrc_remote_dir }}'
        backup: true
      register: bashrc_local_copy
      when: bashrc_local_path is exists

    - name: Source global bashrc
      ansible.builtin.shell:
        cmd: 'echo ". {{ bashrc_remote_dir }}/{{ bashrc_global_file }}" > {{ bashrc_remote_dir }}/bashrc'
        executable: /bin/bash
      when: bashrc_global_copy.changed or bashrc_local_copy.changed

    - name: Source local bashrc
      ansible.builtin.shell:
        cmd: 'echo ". {{ bashrc_remote_dir }}/{{ bashrc_local_file }}" >> {{ bashrc_remote_dir }}/bashrc'
        executable: /bin/bash
      when: bashrc_local_path is exists and bashrc_global_copy.changed or bashrc_local_copy.changed

    - name: Source bashrc in main bashrc
      ansible.builtin.lineinfile:
        path: '~/.bashrc'
        line: '. {{ bashrc_remote_dir }}/bashrc'
        state: present
