- name: Upgrade host
  hosts: "{{ target_host }}"
  tasks:
   - name: Update server
     ansible.builtin.apt:
       name: "*"
       state: latest
       update_cache: yes
       autoremove: true
     become: true
