services:
  nginx-static:
    image: flashspys/nginx-static:latest
    container_name: nginx-static
    volumes:
      - ${NGINX_STATIC_DATA}:/static
    ports:
      - ${NGINX_STATIC_HOST_PORT}:80
    restart: unless-stopped
    networks:
      - nginx_static_network

networks:
  nginx_static_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${NGINX_STATIC_NETWORK}
