services:
  trilium:
    image: triliumnext/trilium:latest
    container_name: trilium
    ports:
      - "8090:8080"
    volumes:
      - ${TRILIUM_DATA}:/home/node/trilium-data
    restart: unless-stopped
    networks:
      - trilium_network

networks:
  trilium_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${TRILIUM_NETWORK}
